name: build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Docker
        run: |
          source docker.env
          docker-compose build
      - name: Test with Rake
        run: |
          docker-compose run --exit-code-from web -e CI=true web bundle exec rake test
        
